### ISSUE TITLE
Inspector state persists through dev server restarts

### ISSUE THREAD

**Issue by arya-s** [suchipi/hex-engine#14]
The inspector state persists when stopping and restarting the dev server in the project created by `create-hex-engine-game`.

If for example we pause rendering, then restart the dev server we come back to an almost blank  page (just the small inspector in the top right showing frame 0). I think this is confusing and looks broken.

**Comment by suchipi** [comment]
This is because whether-the-inspector-is-paused intentionally persists through refreshes so that you can debug frame zero by pausing and refreshing. But I agree it’s weird when you didn’t manually refresh.

**Comment by arya-s** [comment]
Could we inject a variable on server starts and clear based on that?

**Comment by suchipi** [comment]
Yeah, I think we should either do that or set a variable on refresh, if there’s a reliable way to detect that.

Alternatively, we could create a dedicated button for “refresh and pause”, or we could change the UI for the inspector so that its more obvious when you’re paused...

**Comment by suchipi** [comment]
Not sure what the best fix is here; still brainstorming

**Comment by arya-s** [comment]
It's not just pausing that persists right? Maybe having state persist across restarts is fine but the state should have a ttl. I imagine it can be quite frustrating trying to work on your project after a week of break and you can't figure out why the code doesn't behave as you expect only to find it was persistent state from two weeks ago when you last worked on it.

**Comment by suchipi** [comment]
It's pausing and which things are expanded in the tree, though the latter feature needs some work because it might expand the wrong thing if you reorder components or children.

I don't think a TTL is the right fix for this; it would add complexity to it and make it even more confusing. I *do* however intend to eventually add a "collapse all expanded things" button like VS Code's file tree has.

**Comment by suchipi** [comment]
I addressed this (at least partially) in f602cdd30ca9c33e14332556813b2b49ef17a486 by adding a big "play" button to the inspector that shows only when you are paused and on frame zero.

<img width="1440" alt="Screen Shot 2020-01-28 at 6 50 42 PM" src="https://user-images.githubusercontent.com/1341513/73321460-bce7df80-41ff-11ea-88b5-a3852c2f6932.png">

You can update `@hex-engine/2d` to 0.1.14 or higher (in your `package.json`) to get this change.

**Comment by arya-s** [comment]
That's a good indicator, should definitely help not feeling like somethings broken! Thanks for the quick patch.

**Comment by suchipi** [comment]
You're welcome :D

I'm gonna go ahead and close this issue since I think this is good enough for now. Thank you for opening it! I'm really happy that I was able to improve the experience.
