### ISSUE TITLE
Need to bump the version in the `create` package?

### ISSUE THREAD

**Issue by namuol** [suchipi/hex-engine#21]
Looks like the `Point -> Vector` breaking change was applied to the `create` package in https://github.com/suchipi/hex-engine/commit/9f51c49b36f7ddca329d6caf726d11627d6db1f2 but the _version_ for the `create` package hasn't been bumped + published yet, so running `npx create-hex-engine-game` generates a project using `"@hex-engine/2d": "0.2.0"` but still uses `Point` in the actual code.

PS - Loving everything about the engine & tooling so far 👏

**Comment by suchipi** [comment]
ahh, good catch! thanks; I'll fix that.

**Comment by suchipi** [comment]
This is fixed in create-hex-engine-game@0.2.0 (af24ccf5fc4883da677fb8114eba1a186b09b5cc).
