### ISSUE TITLE
Clarify relation of Mouse to Geometry in docs

### ISSUE THREAD

**Issue by kingdaro** [suchipi/hex-engine#26]
The current docs for Mouse reads:

> A Component that gives you information about where the Mouse is, relative to the current Entity, and lets you register functions to be called when the mouse cursor interacts with the current Entity.

This didn't really explain too well where it actually gets the current "area" of the entity from, especially when I'm just looking at a call like `useNewComponent(Mouse)`, which makes it unclear _how_ it knows that the mouse is "in bounds". I had to dig through the source a bit to know that it uses a Geometry passed to it, or a registered Geometry on the entity.

I think it would help to make it explicit in the docs that the Mouse looks for a Geometry component on the entity, and uses that to determine the entity's area.

**Comment by suchipi** [comment]
Thanks for the suggestion! I'll make this change.
