### ISSUE TITLE
Display a spinner when creating a new project

### ISSUE THREAD

**Issue by EmilienLeroy** [suchipi/hex-engine#34]
Hi,
I thinks add a spinner can be good for the user experience when the dependency are installing.
With [ora](https://github.com/sindresorhus/ora) is pretty easy to add this.

For example [here](https://github.com/suchipi/hex-engine/blob/54f3b53cbaa153f3d3d5a7a3f4c429816461c9f4/packages/create/src/index.ts#L7-L15) it can take a while to install.

**Comment by suchipi** [comment]
Great idea! PR welcome
