### ISSUE TITLE
API Proposal: useContext

### ISSUE THREAD

**Issue by coyotte508** [suchipi/hex-engine#46]
## What does this feature solve?

I want to be able to add components to *any* entity whenever I want to.

## Do you have a specific use case?

I have a component called `Attractor` with a rotation/position attached. Every frame, it moves its entity's geometry closer until it reaches the same rotation/position.

When the game state changes, I want to be able to dynamically attach an `Attractor` to any of the game entities.

## What would the new API look like?

The `useContext` function could be a method of `Component` or `Entity`, or it could be a separate funtion.

Here are some examples:

```ts
// As a method
entity.useContext(() => useNewComponent(() => Attractor(...)));
entity.getComponent(...).useContext(() => useNewComponent(() => Attractor(...)));

// As a separate function
useContext(entity, () => useNewComponent(() => Attractor(...))); 
useContext(entity.getComponent(...), (() => useNewComponent(() => Attractor(...)));
```

## Is there an existing workaround?

For this specific use case, I can manually import `instantiate` from `@hex-engine/core/src/instantiate`.

I could also return `{run: useCallbackAsCurrent(f => f())}` in my components, but it's not healthy for the code.

## Do you have an implementation suggestion?

```ts
function useContext<T>(instance: Instance, f: () => T): T {
  return HooksSystem.withInstance(instance, () => f());
});
```

**Comment by coyotte508** [comment]
To make it consistent with `useCallbackAsCurrent`, it could be named `useAsCurrent` instead

**Comment by suchipi** [comment]
Could you elaborate on the need for this? Maybe explain the `Attractor` a bit more?

Is it because you want your component to change its own context when it attaches to different entities?

For cross-entity interaction, I've usually been exposing an API for the entity, and calling methods on it from the other entity, instead of reaching inside and running things on behalf of the entity (in their context). Something like:

```
function Attractable() {
  useType(Attractable);

  function moveTowards(location: Vector, speed: number) {
    // ...
  }

  return {
    moveTowards,
  };
}

function Attractor() {
  useType(Attractor);

  // get an entity somehow...
  const entity = /* whatever */;

  const attractable = entity.getComponent(Attractable);
  if (attractable) {
    attractable.moveTowards(/* ... */);
  }
}
```

Do you feel like this is sufficient?

FYI, I've been trying to avoid exposing useContext directly, because I feel like it's easy to write messy code and get confused if the user changes the current context frequently. `useCallbackAsCurrent` restricts its usage to a form that encourages only worrying about the current context at any given point in a particular component.

**Comment by coyotte508** [comment]
Maybe the naming of the component in the example is bad. For now, I'm using it differently, with one `Attractor` that can have many entities attracted to it:

```ts
function Attractor() {
  useType(Attractor);

  const attracted = new Set<Entity>();
  
  useUpdate() {
    const geometry = useEntity().getComponent(Geometry);

    for (const entity of attracted) {
      // move entity's position, rotation, scale closer to geometry
    }
  }

  return {
    attracted,
    attract(entity: Entity) {
      globalStore.attractedBy(entity)?.attracted.delete(entity);
      attracted.add(entity);
      globalStore.atractedBy.set(entity, this);
    }
  }
}
```

The full code is [currently here](https://github.com/donkeytech/take6-viewer/blob/2fe0cf02d12d40c719e9cc8e455880c0c9209b60/src/Attractor.ts) (the geometry change code itself is messy at the moment).

But I don't really like the idea of using a store to manage conflicts, and it's not as flexible as I'd like.

What I want to do instead is the possibility to set one interpolation target. I.E have this:

```ts
function Interpolation(destPosition: Vector, destRotation: number, destScale: Vector) {
  useType(Interpolation);

  const geometry = useEntity().getComponent(Geometry);

  const {position: startingPosition, rotation: startingRotation, scale: statingScale} = geometry;

  useUpdate(() => {
    // Move geometry closer

    // Possibly remove itself from the entity once the geometry reached its goal
  });
}
```

And it'd be used like:

```ts
useAsCurrent(entity, useNewComponent(() => Interpolation(...)));
```

I do understand the concerns, that's why this is only an API proposal. And it's true that all `Attractable` or `Interpolatable` entities could have a component added to it at their creation, that exposes the necessary function.

Thinking about it, this could be done too:

```ts
function Runnable() {
  useType(Runnable);
  
  return {
    run: useCallbackAsCurrent(f => f())
  }
}

// ...

entity.getComponent(Runnable).run(() => useNewComponent(...));
entity.getComponent(Runnable).run(() => useChild(...));
```

... and it's sufficient for me. Even if sidelining the problem that way may bite me back in the future :)

**Comment by coyotte508** [comment]
I don't know if this is a problem with my way of coding... But I came to this again, when I want to detect items being destroyed. 

I want to do something like:

```
useAsCurrent(otherEntity, () => {
  useDestroy().onDestroy(() => {
    // ...
  });
});
```

That or receive an `event` from the entity:

```
otherEntity.on("destroy", ...);
```

Or do something like: 

```
useDestroy(otherEntity).onDestroy(() => {
  // ...
});
```

**Comment by suchipi** [comment]
I try to keep the list of components an entity will have "static" over its lifetime, and expose an API from the component directly to wire things together and enable/disable different components as needed. I've found that that makes code execution clearer; it's like how the component tree is declarative in React.

I actually did experiment with entities firing events early on in hex engine's development, but it quickly got unruly. 

Could you encapsulate your `onDestroy` callback with whatever else it belongs with, put those both together in a component, and include that component in every entity you want it to do stuff to? To ensure you're only operating on entities that have that component, you could filter the list of entities using `entity.getComponent`.

**Comment by coyotte508** [comment]
@suchipi I fell back to using the `Runner` component (`Runnable` as presented in my previous comment), and I had to add it to a lot of my entities:

```
entity.getComponent(Runner)?.run(() => useDestroy().onDestroy(() => self.unlink(entity)));
```

My use case is not between parent / children, but interactions between possibly completely unrelated entities, and I want to cleanly handle when one of the entities is destroyed. 

While React / the DOM is by nature like a tree, and even siblings very rarely interact (and if they do, it's a very specific behavior already considered at time of implementation), I feel there can be a lot more interaction between entities in a game engine due to the dynamic nature of video games.

For example, let's imagine a game where your character / spaceship shoots a projectile, and can only shoot again when the projectile is destroyed.

The projectile is a child of the scene, as are other entities on the scene, and it can hit any other entity (wall, enemy, box...). It can have data like its size, power, energy but it shouldn't directly have code for the character/spaceship only having a limited number of those projectiles. 

With the same context, imagine an enemy that can temporarily restrain a select number of projectiles. Neither your character nor the projectile itself should have any knowledge of that enemy's code. That enemy should directly be able to get the "destroy" event for the projectile entity to keep count of the currently restrained projectiles, whether it's by the more generic `.run() / useAsCurrent` or a specific way like `useDestroy(entity)`, I don't know.

In those examples, the projectile / character have a relationship (one triggered the creation of another) but are not directly related, and the projectile / enemy did not have any prior relationship, but they still interact. The interaction with another unknown entity can have the effect of needing "event listeners" / adding components that were not originally planned for the entity. It's why I think hex-engine should allow more dynamic interactions, one way or another.

For me personally, the `Runner` component works for that as a fix-everything (why the issue is closed), but I still think it should be builtin, to reduce overhead / simplify code.

**Comment by suchipi** [comment]
I'll think about this some and reply again in the future.

**Comment by suchipi** [comment]
@coyotte508 I've thought about this a lot. If entities had an `addComponent` method (which would pretty much just wrap `instantiate`), would that satisfy this use-case?

**Comment by coyotte508** [comment]
I think it would be a nice addition :)

**Comment by suchipi** [comment]
I've added [addComponent](https://hex-engine.dev/docs/api-core/#addcomponent) (and [removeComponent](https://hex-engine.dev/docs/api-core/#removecomponent)) to Entity in 0.5.2, so I'm closing this.
