### ISSUE TITLE
Error in webpack when building in CI

### ISSUE THREAD

**Issue by PxlBuzzard** [suchipi/hex-engine#78]
I am getting my experimental game pushed out publicly (finally). As part of that process I want to have GitHub Actions publish the game on GitHub Pages using an Action, but I am [hitting an error](https://github.com/PxlBuzzard/game2020/runs/1515014675?check_suite_focus=true) after the build:

```
Creating an optimized production build...
Starting type checking service...
Using 1 worker with 2048MB memory limit

Treating warnings as errors because process.env.CI = true.
Most CI servers set it automatically.

Error: asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  main.js (300 KiB)

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (300 KiB)
      main.js
```

I believe this can be fixed by adding a [larger default max asset size](https://webpack.js.org/configuration/performance/#performancemaxassetsize) to the [webpack config generator](https://github.com/suchipi/hex-engine/blob/master/packages/scripts/src/makeWebpackConfig.ts).

**Comment by suchipi** [comment]
This fix has been published in version 0.8.1. To upgrade, update the version numbers of all Hex Engine packages in your package.json and then run npm install.
